<?php require "assets/header.php"; ?>
<?php
	if(isset($_POST["update_config"])){
		$user_input = array();
		$user_input["backup_limit"] = $_POST["backup_limit"];
		$user_input["notify_email"] = $_POST["notify_email"];
		$user_input["exclusion_days"] = $_POST["exclusion_days"];
		$user_input["exclusion_days_num"] = $_POST["exclusion_days_num"];
		$user_input["ftp_host"] = $_POST["ftp_host"];
		$user_input["ftp_port"] = $_POST["ftp_port"];
		$user_input["ftp_username"] = $_POST["ftp_username"];
		$user_input["ftp_password"] = $_POST["ftp_password"];
		$user_input["ftp_destination"] = $_POST["ftp_destination"];
		
		if($main->config_update($db_conn, $user_input)){
			echo $codeformat->generate_alert("success", "Host Updated Sucessfully.");
		}else{
			echo $codeformat->generate_alert("error", "Host Could Not Be Updated.");
		}
	}

$config = $main->configuration($db_conn);
	
?>

		<h2>Configuration</h2>

		<div class="quick-action-bar">
			<div class="quick-action-content">
				<a href="quick_actions.php?qa=reset_cycle"><div class="quick-action-button"> Reset Cycle </div></a>
				<a href="quick_actions.php?qa=clear_log"><div class="quick-action-button"> Clear Error Log </div></a>
			</div>
		</div>

		<form action="configuration.php" method="post">
			<table class="edit-table">
				<colgroup>
					<col class="edit-col-1">
					<col class="edit-col-2">
				</colgroup>
				<tr>
					<td>Description</td>
					<td>Backup limit will limit how many backups are done on a daily basis. This option will only affect websites selected for monthly backups.</td>
				</tr>
				<tr>
					<td>Backup Limit</td>
					<td><input type="text" name="backup_limit" value="<?php echo $config['backup_limit'] ?>" /></td>
				</tr>
				<tr>
					<td>Description</td>
					<td>Notification E-Mail will be used to send all e-mails generated by the automatic backup script.</td>
				</tr>
				<tr>
					<td>Notification E-Mail</td>
					<td><input type="text" name="notify_email" value="<?php echo $config['notify_email'] ?>" /></td>
				</tr>
				<tr>
					<td>Description</td>
					<td>Exclusion days by day name will exclude listed days every week. (Please use full name and seperate by comma).</td>
				</tr>
				<tr>
					<td>Exclude Days by Name</td>
					<td><input type="text" name="exclusion_days" value="<?php echo $config['exclusion_days'] ?>" /></td>
				</tr>
				<tr>
					<td>Description</td>
					<td>Exclusion days by number will excluded this day every month (Please use comma to seperate).</td>
				</tr>
				<tr>
					<td>Exclude Days by Number</td>
					<td><input type="text" name="exclusion_days_num" value="<?php echo $config['exclusion_days_num'] ?>" /></td>
				</tr>
				<tr>
					<td>Default FTP Info</td>
					<td>Default FTP options will affect all websites that don't have a custom FTP set.</td>
				</tr>
				<tr>
					<td>FTP Host</td>
					<td><input type="text" name="ftp_host" value="<?php echo $config['ftp_default_host'] ?>" /></td>
				</tr>
				<tr>
					<td>FTP Port</td>
					<td><input type="text" name="ftp_port" value="<?php echo $config['ftp_default_port'] ?>" /></td>
				</tr>
				<tr>
					<td>FTP Username</td>
					<td><input type="text" name="ftp_username" value="<?php echo $config['ftp_default_username'] ?>" /></td>
				</tr>
				<tr>
					<td>FTP Password</td>
					<td><input type="text" name="ftp_password" value="<?php echo $config['ftp_default_password'] ?>" /></td>
				</tr>
				<tr>
					<td>FTP Destinination</td>
					<td><input type="text" name="ftp_destination" value="<?php echo $config['ftp_default_destination'] ?>" /></td>
				</tr>
				<tr>
					<td>Update Configuration Options</td>
					<td><input type="submit" name="update_config" id="update_config" value="Update Configuration" /></td>
				</tr>
			</table>
		</form>
			
		<?php require "assets/footer.php"; ?>